/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.debilnicek;

import java.util.List;

/**
 *
 * @author student
 */
public class ZoznamUlohForm extends javax.swing.JFrame {
    
    private UlohaDao zoznamUloh = UlohaDaoFactory.INSTANCE.getUlohaDao();

    /**
     * Creates new form ZoznamUlohForm
     */
    public ZoznamUlohForm() {
        initComponents();
        
        aktualizovatZoznamUloh();
    }

    private void aktualizovatZoznamUloh() {
        // ziskaj model
        UlohaTableModel model = (UlohaTableModel) ulohyTable.getModel();        
        // aktualizuj ho
        model.aktualizovat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popisUlohyTextField = new javax.swing.JTextField();
        pridatUlohuButton = new javax.swing.JButton();
        odstranitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ulohyTable = new javax.swing.JTable();
        pridatKategoriuButton = new javax.swing.JButton();
        kategoriaComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        popisUlohyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popisUlohyTextFieldActionPerformed(evt);
            }
        });

        pridatUlohuButton.setText("Pridať");
        pridatUlohuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatUlohuButtonActionPerformed(evt);
            }
        });

        odstranitButton.setText("Odstrániť");
        odstranitButton.setEnabled(false);
        odstranitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odstranitButtonActionPerformed(evt);
            }
        });

        ulohyTable.setModel(new UlohaTableModel());
        jScrollPane2.setViewportView(ulohyTable);

        pridatKategoriuButton.setText("Pridať kategóriu...");
        pridatKategoriuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatKategoriuButtonActionPerformed(evt);
            }
        });

        kategoriaComboBox.setModel(new KategoriaComboBoxModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(popisUlohyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(kategoriaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pridatKategoriuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pridatUlohuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(odstranitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popisUlohyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pridatUlohuButton)
                    .addComponent(odstranitButton))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridatKategoriuButton)
                    .addComponent(kategoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popisUlohyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popisUlohyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popisUlohyTextFieldActionPerformed

    private void pridatUlohuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatUlohuButtonActionPerformed
        String popisUlohy = popisUlohyTextField.getText();
        
        Uloha uloha = new Uloha();
        uloha.setPopis(popisUlohy);
        
        zoznamUloh.pridaj(uloha);
        
        aktualizovatZoznamUloh();
    }//GEN-LAST:event_pridatUlohuButtonActionPerformed

    private void odstranitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odstranitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odstranitButtonActionPerformed

    private void pridatKategoriuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatKategoriuButtonActionPerformed
        KategoriaForm kategoriaForm = new KategoriaForm(this, true);
        kategoriaForm.setVisible(true);
      
        //----
        ( (KategoriaComboBoxModel) kategoriaComboBox.getModel() ).refresh();
    }//GEN-LAST:event_pridatKategoriuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZoznamUlohForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZoznamUlohForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZoznamUlohForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZoznamUlohForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZoznamUlohForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Kategoria> kategoriaComboBox;
    private javax.swing.JButton odstranitButton;
    private javax.swing.JTextField popisUlohyTextField;
    private javax.swing.JButton pridatKategoriuButton;
    private javax.swing.JButton pridatUlohuButton;
    private javax.swing.JTable ulohyTable;
    // End of variables declaration//GEN-END:variables
}
